services:
  db:
    image: mysql:8.0.28
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=conifers
    command: [
      '--wait_timeout=86400',
    ]
    restart: always
    ports:
      - "17843:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    ports:
      - "8080:80"