# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "infra/repository_impl/src/diesel_based_impl/schema.rs"

[migrations_directory]
dir = "database/migrations"
