[package]
name = "infra_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }

anyhow = "1.0.60"
async-trait = "0.1.57"
log = "0.4.17"
pbjson-types = "0.3.2"
prost = "0.10.4"
serde = "1.0.143"
tonic = { version = "0.7.2", features = ["compression"] }
