version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/community/neoeinstein-prost:v0.2.2
    out: src/gen
    opt:
      # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-prost#options
      - bytes=.
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
      - file_descriptor_set
  - plugin: buf.build/community/neoeinstein-tonic:v0.2.2
    out: src/gen
    opt:
      # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-tonic
      - compile_well_known_types
      - extern_path=.google.protobuf=::pbjson_types
  - plugin: buf.build/community/neoeinstein-prost-crate:v0.3.1
    out: src/gen
    # https://github.com/neoeinstein/protoc-gen-prost/tree/main/protoc-gen-prost-crate
    opt:
      - no_features
