name: build test

on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            /root/.ivy2/cache
            /root/.cache/coursier
            /root/.sbt
          key: ${{ runner.os }}-scala-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-scala-cache-
      - name: build
        run: sbt assembly
