name: Check for scalafmt and scalafix

on:
  pull_request:
    branches:
      - master

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - name: execute scalafmt lint
        run: sbt scalafmtCheckAll
  scalafix-lint:
    runs-on: ubuntu-latest
    steps:
      - name: execute scalafix lint
        run: sbt "scalafix --check"


